#!/usr/bin/env python3
import os
import re
from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parent.parent
TOPICS_DIR = ROOT_DIR / "topics"
README_PATH = ROOT_DIR / "README.md"

TABLE_HEADER = "| # | Title | Difficulty | Topic | Solution |\n"
TABLE_DIVIDER = "|---|-------|-----------|-------|----------|\n"

DIFFICULTY_EMOJI = {
    "Easy": "🟢",
    "Medium": "🟡",
    "Hard": "🔴",
}


def parse_problem_readme(readme_path: Path):
    """Extract number, title, difficulty, tags, and link from a problem README."""
    text = readme_path.read_text(encoding="utf-8")

    title_match = re.search(r"#\s*(\d+)\.\s*(.+)", text)
    number = title_match.group(1) if title_match else "?"
    title = title_match.group(2).strip() if title_match else readme_path.parent.name

    link_match = re.search(r"\[LeetCode Link\]\((.+?)\)", text)
    link = link_match.group(1) if link_match else ""

    difficulty_match = re.search(r"\*\*Difficulty:\*\*\s*(\w+)", text)
    difficulty = difficulty_match.group(1) if difficulty_match else "Unknown"

    tags_match = re.search(r"\*\*Tags:\*\*\s*(.+)", text)
    tags = tags_match.group(1).strip() if tags_match else ""

    return {
        "number": int(number) if number.isdigit() else 0,
        "title": title,
        "difficulty": difficulty,
        "tags": tags,
        "link": link,
    }


def collect_problems():
    problems = []

    if not TOPICS_DIR.exists():
        print(f"No topics/ directory found at {TOPICS_DIR}")
        return problems

    for topic_dir in sorted(TOPICS_DIR.iterdir()):
        if not topic_dir.is_dir():
            continue

        topic_name = topic_dir.name.replace("-", " ").title()

        for problem_dir in sorted(topic_dir.iterdir()):
            readme_file = problem_dir / "README.md"
            if not problem_dir.is_dir() or not readme_file.exists():
                continue

            data = parse_problem_readme(readme_file)
            data["topic"] = topic_name
            data["folder"] = f"topics/{topic_dir.name}/{problem_dir.name}"
            problems.append(data)

    problems.sort(key=lambda p: p["number"])
    return problems


def build_table(problems):
    if not problems:
        return "_No problems added yet. Run this script after adding your first solution._\n"

    rows = [TABLE_HEADER, TABLE_DIVIDER]
    for p in problems:
        emoji = DIFFICULTY_EMOJI.get(p["difficulty"], "")
        difficulty_display = f"{emoji} {p['difficulty']}".strip()
        rows.append(
            f"| {p['number']} | {p['title']} | {difficulty_display} | "
            f"{p['topic']} | [Solution]({p['folder']}) |\n"
        )
    return "".join(rows)


def build_stats(problems):
    total = len(problems)
    counts = {"Easy": 0, "Medium": 0, "Hard": 0}
    for p in problems:
        if p["difficulty"] in counts:
            counts[p["difficulty"]] += 1

    return (
        f"**Total solved:** {total}  \n"
        f"🟢 Easy: {counts['Easy']}  |  "
        f"🟡 Medium: {counts['Medium']}  |  "
        f"🔴 Hard: {counts['Hard']}\n"
    )


def write_readme(problems):
    table = build_table(problems)
    stats = build_stats(problems)

    content = f"""# LeetCode Solutions

A collection of my LeetCode problem solutions, organized by topic/pattern.

{stats}

## Index

{table}

---
_This README is auto-generated by `scripts/generate_readme.py`. Do not edit the table manually._
"""

    README_PATH.write_text(content, encoding="utf-8")
    print(f"README.md updated with {len(problems)} problems.")


if __name__ == "__main__":
    problems = collect_problems()
    write_readme(problems)
